---
- hosts: webdev
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - ansible-role-user
    - ansible-role-docker
    - ansible-role-docker-compose
    - ansible-role-docker-nginx
    - ansible-role-docker-postgres
    - ansible-role-docker-mysql
    - ansible-role-docker-python
    - ansible-role-docker-node